name: CCheck

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install environment
        run: env

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install build essential
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build io_flush
        run: |
          cd 01.IO_flush
          make

      - name: Upload io_flush
        uses: actions/upload-artifact@v4
        with:
          name: io_flush
          path: ${{ github.workspace }}/01.IO_flush

      - name: Build fractal
        run: |
          cd 03.Fractal
          make

      - name: Upload fractal
        uses: actions/upload-artifact@v4
        with:
          name: fractal
          path: ${{ github.workspace }}/03.Fractal

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download io_flush
        uses: actions/download-artifact@v4
        with:
          name: io_flush
          path: 01.IO_flush

      - name: Test io_flush
        run: |
          cd 01.IO_flush
          chmod u+x io_flush
          chmod u+x experiment.bash
          ./experiment.bash

      - name: Download fractal
        uses: actions/download-artifact@v4
        with:
          name: fractal
          path: 03.Fractal

      - name: Test fractal
        run: |
          cd 03.Fractal
          chmod u+x fractal
          ./fractal
