name: ShellCheck
    
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: tty
          path: "."